<a href="https://colab.research.google.com/github/Devdat24/Smart-Student-Analyzer/blob/main/spp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
df.info(), df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                395 non-null    int64
 1   Medu               395 non-null    int64
 2   Fedu               395 non-null    int64
 3   traveltime         395 non-null    int64
 4   studytime          395 non-null    int64
 5   failures           395 non-null    int64
 6   famrel             395 non-null    int64
 7   freetime           395 non-null    int64
 8   goout              395 non-null    int64
 9   Dalc               395 non-null    int64
 10  Walc               395 non-null    int64
 11  health             395 non-null    int64
 12  absences           395 non-null    int64
 13  G1                 395 non-null    int64
 14  G2                 395 non-null    int64
 15  G3                 395 non-null    int64
 16  school_MS          395 non-null    bool
 17  sex_M              395 non-null    bool
 18  address_U          395 non-null    bool
 19  famsize_LE3        395 non-null    bool
 20  Pstatus_T          395 non-null    bool
 21  Mjob_health        395 non-null    bool
 22  Mjob_other         395 non-null    bool
 23  Mjob_services      395 non-null    bool
 24  Mjob_teacher       395 non-null    bool
 25  Fjob_health        395 non-null    bool
 26  Fjob_other         395 non-null    bool
 27  Fjob_services      395 non-null    bool
 28  Fjob_teacher       395 non-null    bool
 29  reason_home        395 non-null    bool
 30  reason_other       395 non-null    bool
 31  reason_reputation  395 non-null    bool
 32  guardian_mother    395 non-null    bool
 33  guardian_other     395 non-null    bool
 34  schoolsup_yes      395 non-null    bool
 35  famsup_yes         395 non-null    bool
 36  paid_yes           395 non-null    bool
 37  activities_yes     395 non-null    bool
 38  nursery_yes        395 non-null    bool
 39  higher_yes         395 non-null    bool
 40  internet_yes       395 non-null    bool
 41  romantic_yes       395 non-null    bool
dtypes: bool(26), int64(16)
memory usage: 59.5 KB

(None,
               age        Medu        Fedu  traveltime   studytime    failures  \
 count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
 mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177
 std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651
 min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000
 25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000
 50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000
 75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000
 max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000

            famrel    freetime       goout        Dalc        Walc      health  \
 count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
 mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430
 std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303
 min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
 25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000
 50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
 75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
 max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

          absences          G1          G2          G3
 count  395.000000  395.000000  395.000000  395.000000
 mean     5.708861   10.908861   10.713924   10.415190
 std      8.003096    3.319195    3.761505    4.581443
 min      0.000000    3.000000    0.000000    0.000000
 25%      0.000000    8.000000    9.000000    8.000000
 50%      4.000000   11.000000   11.000000   11.000000
 75%      8.000000   13.000000   13.000000   14.000000
 max     75.000000   19.000000   19.000000   20.000000  )

In [ ]:
df.shape

(395, 42)

In [ ]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [ ]:
df = pd.get_dummies(df, drop_first=True)

In [ ]:
df.to_csv('cleaned_student.csv', index=False)

In [ ]:
from google.colab import files
files.download('cleaned_student.csv')